var annotated_dup =
[
    [ "gs", "namespacegs.html", [
      [ "animation", "namespacegs_1_1animation.html", [
        [ "Key", "structgs_1_1animation_1_1Key.html", "structgs_1_1animation_1_1Key" ],
        [ "Keyframe", "structgs_1_1animation_1_1Keyframe.html", "structgs_1_1animation_1_1Keyframe" ],
        [ "PropertyValue", "structgs_1_1animation_1_1PropertyValue.html", "structgs_1_1animation_1_1PropertyValue" ],
        [ "KeyframeCollection", "structgs_1_1animation_1_1KeyframeCollection.html", "structgs_1_1animation_1_1KeyframeCollection" ],
        [ "SubProperty", "structgs_1_1animation_1_1SubProperty.html", "structgs_1_1animation_1_1SubProperty" ],
        [ "PropertyPath", "structgs_1_1animation_1_1PropertyPath.html", "structgs_1_1animation_1_1PropertyPath" ],
        [ "FloatSpanAdapter", "classgs_1_1animation_1_1FloatSpanAdapter.html", null ],
        [ "FloatSpanAdapter&lt; float &gt;", "classgs_1_1animation_1_1FloatSpanAdapter_3_01float_01_4.html", null ],
        [ "FloatSpanAdapter&lt; Vec3 &gt;", "classgs_1_1animation_1_1FloatSpanAdapter_3_01Vec3_01_4.html", null ],
        [ "FloatSpanAdapter&lt; Color &gt;", "classgs_1_1animation_1_1FloatSpanAdapter_3_01Color_01_4.html", null ],
        [ "FloatSpanAdapter&lt; scene::Point &gt;", "classgs_1_1animation_1_1FloatSpanAdapter_3_01scene_1_1Point_01_4.html", null ],
        [ "FloatSpanAdapter&lt; Camera &gt;", "classgs_1_1animation_1_1FloatSpanAdapter_3_01Camera_01_4.html", null ],
        [ "Handle", "structgs_1_1animation_1_1Handle.html", "structgs_1_1animation_1_1Handle" ],
        [ "IManager", "classgs_1_1animation_1_1IManager.html", "classgs_1_1animation_1_1IManager" ],
        [ "Manager", "classgs_1_1animation_1_1Manager.html", "classgs_1_1animation_1_1Manager" ],
        [ "IPlayerManager", "classgs_1_1animation_1_1IPlayerManager.html", "classgs_1_1animation_1_1IPlayerManager" ],
        [ "PlayerManager", "classgs_1_1animation_1_1PlayerManager.html", "classgs_1_1animation_1_1PlayerManager" ],
        [ "Sampler", "classgs_1_1animation_1_1Sampler.html", "classgs_1_1animation_1_1Sampler" ],
        [ "ReversableAnimation", "classgs_1_1animation_1_1ReversableAnimation.html", "classgs_1_1animation_1_1ReversableAnimation" ],
        [ "IService", "classgs_1_1animation_1_1IService.html", "classgs_1_1animation_1_1IService" ],
        [ "Service", "classgs_1_1animation_1_1Service.html", "classgs_1_1animation_1_1Service" ],
        [ "Target", "structgs_1_1animation_1_1Target.html", "structgs_1_1animation_1_1Target" ],
        [ "Asset", "structgs_1_1animation_1_1Asset.html", "structgs_1_1animation_1_1Asset" ],
        [ "Instance", "structgs_1_1animation_1_1Instance.html", "structgs_1_1animation_1_1Instance" ],
        [ "AssetCollection", "structgs_1_1animation_1_1AssetCollection.html", "structgs_1_1animation_1_1AssetCollection" ],
        [ "Clip", "structgs_1_1animation_1_1Clip.html", "structgs_1_1animation_1_1Clip" ]
      ] ],
      [ "reflection", "namespacegs_1_1reflection.html", [
        [ "Property", "structgs_1_1reflection_1_1Property.html", "structgs_1_1reflection_1_1Property" ]
      ] ],
      [ "ecs", "namespacegs_1_1ecs.html", [
        [ "component", "namespacegs_1_1ecs_1_1component.html", [
          [ "Arrow", "structgs_1_1ecs_1_1component_1_1Arrow.html", "structgs_1_1ecs_1_1component_1_1Arrow" ],
          [ "MainColor", "structgs_1_1ecs_1_1component_1_1MainColor.html", "structgs_1_1ecs_1_1component_1_1MainColor" ],
          [ "Normal", "structgs_1_1ecs_1_1component_1_1Normal.html", "structgs_1_1ecs_1_1component_1_1Normal" ],
          [ "Distance", "structgs_1_1ecs_1_1component_1_1Distance.html", "structgs_1_1ecs_1_1component_1_1Distance" ],
          [ "Position", "structgs_1_1ecs_1_1component_1_1Position.html", "structgs_1_1ecs_1_1component_1_1Position" ],
          [ "EndPosition", "structgs_1_1ecs_1_1component_1_1EndPosition.html", "structgs_1_1ecs_1_1component_1_1EndPosition" ],
          [ "Radius", "structgs_1_1ecs_1_1component_1_1Radius.html", "structgs_1_1ecs_1_1component_1_1Radius" ],
          [ "AABBSize", "structgs_1_1ecs_1_1component_1_1AABBSize.html", "structgs_1_1ecs_1_1component_1_1AABBSize" ],
          [ "Thickness", "structgs_1_1ecs_1_1component_1_1Thickness.html", "structgs_1_1ecs_1_1component_1_1Thickness" ],
          [ "Label", "structgs_1_1ecs_1_1component_1_1Label.html", "structgs_1_1ecs_1_1component_1_1Label" ],
          [ "SphereCollider", "structgs_1_1ecs_1_1component_1_1SphereCollider.html", "structgs_1_1ecs_1_1component_1_1SphereCollider" ],
          [ "AABBCollider", "structgs_1_1ecs_1_1component_1_1AABBCollider.html", "structgs_1_1ecs_1_1component_1_1AABBCollider" ],
          [ "Dashed", "structgs_1_1ecs_1_1component_1_1Dashed.html", "structgs_1_1ecs_1_1component_1_1Dashed" ],
          [ "Selected", "structgs_1_1ecs_1_1component_1_1Selected.html", null ],
          [ "OnSelectCallback", "structgs_1_1ecs_1_1component_1_1OnSelectCallback.html", "structgs_1_1ecs_1_1component_1_1OnSelectCallback" ],
          [ "Hovered", "structgs_1_1ecs_1_1component_1_1Hovered.html", null ],
          [ "OnHoverCallback", "structgs_1_1ecs_1_1component_1_1OnHoverCallback.html", "structgs_1_1ecs_1_1component_1_1OnHoverCallback" ],
          [ "Translated", "structgs_1_1ecs_1_1component_1_1Translated.html", "structgs_1_1ecs_1_1component_1_1Translated" ],
          [ "OnTranslateCallback", "structgs_1_1ecs_1_1component_1_1OnTranslateCallback.html", "structgs_1_1ecs_1_1component_1_1OnTranslateCallback" ]
        ] ]
      ] ],
      [ "scene", "namespacegs_1_1scene.html", [
        [ "Grid2D", "structgs_1_1scene_1_1Grid2D.html", "structgs_1_1scene_1_1Grid2D" ],
        [ "Plane", "structgs_1_1scene_1_1Plane.html", "structgs_1_1scene_1_1Plane" ],
        [ "Point", "structgs_1_1scene_1_1Point.html", "structgs_1_1scene_1_1Point" ],
        [ "DashedLine", "structgs_1_1scene_1_1DashedLine.html", "structgs_1_1scene_1_1DashedLine" ],
        [ "Text", "structgs_1_1scene_1_1Text.html", "structgs_1_1scene_1_1Text" ],
        [ "Vector", "structgs_1_1scene_1_1Vector.html", "structgs_1_1scene_1_1Vector" ],
        [ "AABB", "structgs_1_1scene_1_1AABB.html", "structgs_1_1scene_1_1AABB" ]
      ] ],
      [ "ui", "namespacegs_1_1ui.html", [
        [ "Layout", "structgs_1_1ui_1_1Layout.html", "structgs_1_1ui_1_1Layout" ],
        [ "Element", "structgs_1_1ui_1_1Element.html", "structgs_1_1ui_1_1Element" ],
        [ "Button", "structgs_1_1ui_1_1Button.html", "structgs_1_1ui_1_1Button" ],
        [ "Slider", "structgs_1_1ui_1_1Slider.html", "structgs_1_1ui_1_1Slider" ],
        [ "AnimationPlayer", "structgs_1_1ui_1_1AnimationPlayer.html", "structgs_1_1ui_1_1AnimationPlayer" ],
        [ "State", "structgs_1_1ui_1_1State.html", "structgs_1_1ui_1_1State" ]
      ] ],
      [ "Application", "classgs_1_1Application.html", "classgs_1_1Application" ],
      [ "ICameraControllerService", "classgs_1_1ICameraControllerService.html", "classgs_1_1ICameraControllerService" ],
      [ "CameraControllerService", "classgs_1_1CameraControllerService.html", "classgs_1_1CameraControllerService" ],
      [ "ICameraService", "classgs_1_1ICameraService.html", "classgs_1_1ICameraService" ],
      [ "CameraService", "classgs_1_1CameraService.html", "classgs_1_1CameraService" ],
      [ "ICanvasService", "classgs_1_1ICanvasService.html", "classgs_1_1ICanvasService" ],
      [ "CanvasService", "classgs_1_1CanvasService.html", "classgs_1_1CanvasService" ],
      [ "IInputManager", "classgs_1_1IInputManager.html", "classgs_1_1IInputManager" ],
      [ "InputManager", "classgs_1_1InputManager.html", "classgs_1_1InputManager" ],
      [ "IJsonService", "classgs_1_1IJsonService.html", "classgs_1_1IJsonService" ],
      [ "JsonService", "classgs_1_1JsonService.html", "classgs_1_1JsonService" ],
      [ "ILogManager", "classgs_1_1ILogManager.html", "classgs_1_1ILogManager" ],
      [ "LogManager", "classgs_1_1LogManager.html", "classgs_1_1LogManager" ],
      [ "Ray", "structgs_1_1Ray.html", "structgs_1_1Ray" ],
      [ "Sphere", "structgs_1_1Sphere.html", "structgs_1_1Sphere" ],
      [ "AABB", "structgs_1_1AABB.html", "structgs_1_1AABB" ],
      [ "Plane", "structgs_1_1Plane.html", "structgs_1_1Plane" ],
      [ "Intersection", "structgs_1_1Intersection.html", "structgs_1_1Intersection" ],
      [ "IRenderService", "classgs_1_1IRenderService.html", "classgs_1_1IRenderService" ],
      [ "RenderService", "classgs_1_1RenderService.html", "classgs_1_1RenderService" ],
      [ "IResourceManager", "classgs_1_1IResourceManager.html", "classgs_1_1IResourceManager" ],
      [ "ResourceManager", "classgs_1_1ResourceManager.html", "classgs_1_1ResourceManager" ],
      [ "ISceneService", "classgs_1_1ISceneService.html", "classgs_1_1ISceneService" ],
      [ "SceneService", "classgs_1_1SceneService.html", "classgs_1_1SceneService" ],
      [ "Settings", "structgs_1_1Settings.html", "structgs_1_1Settings" ],
      [ "RectSize", "structgs_1_1RectSize.html", "structgs_1_1RectSize" ],
      [ "Color", "structgs_1_1Color.html", "structgs_1_1Color" ],
      [ "TranslateGizmo", "structgs_1_1TranslateGizmo.html", "structgs_1_1TranslateGizmo" ],
      [ "Camera", "structgs_1_1Camera.html", "structgs_1_1Camera" ],
      [ "PerformanceStats", "structgs_1_1PerformanceStats.html", "structgs_1_1PerformanceStats" ],
      [ "IWindowManager", "classgs_1_1IWindowManager.html", "classgs_1_1IWindowManager" ],
      [ "WindowManager", "classgs_1_1WindowManager.html", "classgs_1_1WindowManager" ],
      [ "ICameraIdleRotationManager", "classgs_1_1ICameraIdleRotationManager.html", "classgs_1_1ICameraIdleRotationManager" ],
      [ "CameraIdleRotationAnimationManager", "classgs_1_1CameraIdleRotationAnimationManager.html", "classgs_1_1CameraIdleRotationAnimationManager" ],
      [ "IOrthoProjectionViewManager", "classgs_1_1IOrthoProjectionViewManager.html", "classgs_1_1IOrthoProjectionViewManager" ],
      [ "OrthoProjectionViewManager", "classgs_1_1OrthoProjectionViewManager.html", "classgs_1_1OrthoProjectionViewManager" ],
      [ "IInteractionService", "classgs_1_1IInteractionService.html", "classgs_1_1IInteractionService" ],
      [ "InteractionService", "classgs_1_1InteractionService.html", "classgs_1_1InteractionService" ],
      [ "ITranslateGizmoRenderService", "classgs_1_1ITranslateGizmoRenderService.html", "classgs_1_1ITranslateGizmoRenderService" ],
      [ "TranslateGizmoRenderService", "classgs_1_1TranslateGizmoRenderService.html", "classgs_1_1TranslateGizmoRenderService" ],
      [ "ITranslateGizmoUpdateService", "classgs_1_1ITranslateGizmoUpdateService.html", "classgs_1_1ITranslateGizmoUpdateService" ],
      [ "TranslateGizmoUpdateService", "classgs_1_1TranslateGizmoUpdateService.html", "classgs_1_1TranslateGizmoUpdateService" ],
      [ "IUIManager", "classgs_1_1IUIManager.html", "classgs_1_1IUIManager" ],
      [ "UIManager", "classgs_1_1UIManager.html", "classgs_1_1UIManager" ],
      [ "IUIService", "classgs_1_1IUIService.html", "classgs_1_1IUIService" ],
      [ "UIService", "classgs_1_1UIService.html", "classgs_1_1UIService" ]
    ] ],
    [ "SlotMap", "classSlotMap.html", "classSlotMap" ]
];