name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build `
        -DCMAKE_BUILD_TYPE=Release `
        -DGSAND_ENABLE_TESTS=OFF `
        -DGSAND_ENABLE_BENCHMARKS=OFF `
        -DGSAND_BUILD_DOCS=OFF `
        -DGSAND_BUILD_SAMPLES=ON `
        -DGSAND_USE_CLANG_TIDY=OFF

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: geometry-sandbox-windows
        path: build/Release/
